Dev continued UI improvements
phillip-niakoulov/307-ecommerce-site pull request #31
Opened 2024-11-20 06:04 UTC by heyitsjorge

Register UI has been implemented.

Some comments from the previous CSS files have been added and cleaned up.

2024-11-20 06:24 UTC, curtisjbradley commented
Looks good. Make sure to add a page header to the register page.

2024-11-20 06:26 UTC, curtisjbradley requested changes
Make sure the register page has a header.

2024-11-20 07:31 UTC, phillip-niakoulov commented
Looks sick.

2024-11-21 04:09 UTC, edsonmunoz commented on frontend/src/styles/pages/notfound.css
way to clean up the code

2024-11-21 04:09 UTC, edsonmunoz commented on frontend/src/styles/pages/register.css
nice styles, looks good!!!

2024-11-21 05:03 UTC, curtisjbradley reviewed
Looks good.

2024-11-21 05:03 UTC, curtisjbradley commented on frontend/src/pages/Register.jsx
> +            <h1>Register</h1>
Added Header

2024-11-21 05:05 UTC, merged